# Generated by Django 5.2.8 on 2025-12-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_delivery_charge_order_delivery_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cod_shipping_paid",
            field=models.BooleanField(
                default=False,
                help_text="Whether shipping cost has been paid for COD orders",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cod_shipping_transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Transaction ID for shipping cost payment on COD orders",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
