# Generated by Django 5.2.8 on 2026-04-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="low_stock_threshold",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock_quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="track_inventory",
        ),
        migrations.AddField(
            model_name="product",
            name="is_digital",
            field=models.BooleanField(default=False),
        ),
    ]
