# Generated by Django 5.2.8 on 2026-04-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_drop_product_stock_add_variant"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="vendors.vendor",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["vendor", "is_active"], name="products_vendor__e7f485_idx"
            ),
        ),
    ]
