# Generated by Django 5.2.8 on 2026-04-25 14:59

from django.db import migrations


def backfill_product_vendor(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Vendor = apps.get_model("vendors", "Vendor")

    vendor = Vendor.objects.order_by("created_at").first()
    if vendor:
        Product.objects.filter(vendor__isnull=True).update(vendor_id=vendor.id)


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_vendor_product_products_vendor__e7f485_idx"),
        ("vendors", "0002_default_vendor_memberships"),
    ]

    operations = [
        migrations.RunPython(backfill_product_vendor, migrations.RunPython.noop),
    ]

