# Generated by Django 5.2.8 on 2026-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="free_shipping_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=1000,
                help_text="Orders at or above this amount qualify for free shipping. Set to 0 to disable free shipping.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="inside_dhaka_delivery_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=60,
                help_text="Delivery charge for orders within Dhaka city (BDT)",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="outside_dhaka_delivery_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=120,
                help_text="Delivery charge for orders outside Dhaka city (BDT)",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tax percentage applied to the order total (e.g. 5 means 5%). Set to 0 for no tax.",
                max_digits=5,
            ),
        ),
    ]
