# Generated by Django 5.2.8 on 2026-04-14 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_add_shipping_tax_config_to_siteconfig"),
        ("store", "0002_siteconfig_meta_fields"),
    ]

    operations = []

