# Generated by Django 5.2.8 on 2026-04-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_merge_0002_siteconfig_fields"),
        ("vendors", "0004_copy_siteconfig_meta_to_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfig",
            name="meta_access_token",
        ),
        migrations.RemoveField(
            model_name="siteconfig",
            name="meta_capi_enabled",
        ),
        migrations.RemoveField(
            model_name="siteconfig",
            name="meta_default_currency",
        ),
        migrations.RemoveField(
            model_name="siteconfig",
            name="meta_pixel_enabled",
        ),
        migrations.RemoveField(
            model_name="siteconfig",
            name="meta_pixel_id",
        ),
        migrations.RemoveField(
            model_name="siteconfig",
            name="meta_test_event_code",
        ),
    ]
