# Generated by Django 5.2.8 on 2026-04-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_copy_meta_from_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="free_shipping_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Orders at or above this amount qualify for free shipping. Set to 0 to disable free shipping.",
                max_digits=8,
            ),
        ),
    ]
