# Generated by Django 5.2.8 on 2026-04-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("products", "0004_product_vendor_product_products_vendor__e7f485_idx"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="finishedgoodsreceipt",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finished_goods_receipts",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_categories",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials",
                to="inventory.materialcategory",
            ),
        ),
        migrations.AddField(
            model_name="materialtransaction",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="inventory.material",
            ),
        ),
        migrations.AddField(
            model_name="materialtransaction",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_transactions",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="productionbatch",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_batches",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="productionbatchmaterial",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="inventory.productionbatch",
            ),
        ),
        migrations.AddField(
            model_name="productionbatchmaterial",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batch_materials",
                to="inventory.material",
            ),
        ),
        migrations.AddField(
            model_name="productionbatchoutput",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outputs",
                to="inventory.productionbatch",
            ),
        ),
        migrations.AddField(
            model_name="productionbatchoutput",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_outputs",
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="variantstocktransaction",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_transactions",
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="variantstocktransaction",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_stock_transactions",
                to="vendors.vendor",
            ),
        ),
        migrations.AddIndex(
            model_name="finishedgoodsreceipt",
            index=models.Index(
                fields=["vendor", "received_at"], name="finished_go_vendor__5ed474_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="materialcategory",
            constraint=models.UniqueConstraint(
                fields=("vendor", "name"), name="unique_material_category_per_vendor"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["vendor", "is_active"], name="materials_vendor__5bb241_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="material",
            constraint=models.UniqueConstraint(
                fields=("vendor", "sku"), name="unique_material_sku_per_vendor"
            ),
        ),
        migrations.AddIndex(
            model_name="materialtransaction",
            index=models.Index(
                fields=["vendor", "material", "created_at"],
                name="material_tr_vendor__a33aca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialtransaction",
            index=models.Index(
                fields=["transaction_type", "created_at"],
                name="material_tr_transac_afb806_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionbatch",
            constraint=models.UniqueConstraint(
                fields=("vendor", "code"), name="unique_batch_code_per_vendor"
            ),
        ),
        migrations.AddConstraint(
            model_name="productionbatchmaterial",
            constraint=models.UniqueConstraint(
                fields=("batch", "material"), name="unique_material_per_batch"
            ),
        ),
        migrations.AddConstraint(
            model_name="productionbatchoutput",
            constraint=models.UniqueConstraint(
                fields=("batch", "variant"), name="unique_variant_output_per_batch"
            ),
        ),
        migrations.AddIndex(
            model_name="variantstocktransaction",
            index=models.Index(
                fields=["vendor", "variant", "created_at"],
                name="variant_sto_vendor__3b6ec7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="variantstocktransaction",
            index=models.Index(
                fields=["transaction_type", "created_at"],
                name="variant_sto_transac_245f52_idx",
            ),
        ),
    ]
