# Generated by Django 5.2.8 on 2026-04-03 04:49

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed Amount"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0-100) or fixed amount",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("all_products", "All Products"),
                            ("specific_categories", "Specific Categories"),
                            ("specific_products", "Specific Products"),
                        ],
                        default="specific_products",
                        max_length=25,
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                (
                    "allow_coupon_stacking",
                    models.BooleanField(
                        default=True,
                        help_text="Allow coupon codes to be applied on top of this sale discount",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="sales", to="products.category"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="sales", to="products.product"
                    ),
                ),
            ],
            options={
                "db_table": "sales",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "valid_from", "valid_until"],
                        name="sales_is_acti_5f3f1b_idx",
                    ),
                    models.Index(
                        fields=["applies_to"], name="sales_applies_106f06_idx"
                    ),
                ],
            },
        ),
    ]
