# Generated by Django 5.2.8 on 2026-04-25 14:59

from django.db import migrations


DEFAULT_CATEGORIES = [
    "Purchase",
    "Labor / Making Cost",
    "Transport",
    "Customs",
    "Packaging",
    "Advertising",
    "Utilities",
    "Rent",
    "Miscellaneous",
]


def seed_expense_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model("expenses", "ExpenseCategory")

    for name in DEFAULT_CATEGORIES:
        ExpenseCategory.objects.get_or_create(
            vendor_id=None,
            name=name,
            defaults={
                "slug": name.lower().replace(" / ", "-").replace(" ", "-"),
                "is_active": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_initial"),
    ]

    operations = [
        migrations.RunPython(seed_expense_categories, migrations.RunPython.noop),
    ]

