# Generated by Django 5.2.8 on 2026-04-25 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("inventory_enabled", models.BooleanField(default=False)),
                ("expenses_enabled", models.BooleanField(default=True)),
                (
                    "inventory_mode",
                    models.CharField(
                        choices=[
                            ("trading", "Trading"),
                            ("manufacturing", "Manufacturing"),
                        ],
                        default="trading",
                        max_length=20,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_vendors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vendors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VendorMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_owner", models.BooleanField(default=False)),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_memberships",
                        to="users.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_memberships",
                "ordering": ["-is_owner", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["slug", "is_active"], name="vendors_slug_a7e02c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendormembership",
            index=models.Index(
                fields=["vendor", "user", "is_active"],
                name="vendor_memb_vendor__c16af3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vendormembership",
            index=models.Index(
                fields=["user", "is_active"], name="vendor_memb_user_id_93b413_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendormembership",
            constraint=models.UniqueConstraint(
                fields=("vendor", "user"), name="unique_vendor_membership"
            ),
        ),
    ]
