# Generated by Django 5.2.8 on 2026-04-25 14:59

from django.db import migrations


def create_default_vendor(apps, schema_editor):
    User = apps.get_model("users", "User")
    Vendor = apps.get_model("vendors", "Vendor")
    VendorMembership = apps.get_model("vendors", "VendorMembership")

    owner = (
        User.objects.filter(is_superuser=True).order_by("created_at").first()
        or User.objects.filter(is_staff=True).order_by("created_at").first()
        or User.objects.order_by("created_at").first()
    )

    vendor, _ = Vendor.objects.get_or_create(
        slug="default-vendor",
        defaults={
            "name": "Default Vendor",
            "owner_id": owner.id if owner else None,
            "inventory_enabled": True,
            "expenses_enabled": True,
            "inventory_mode": "trading",
            "is_active": True,
        },
    )

    if owner and vendor.owner_id != owner.id:
        vendor.owner_id = owner.id
        vendor.save(update_fields=["owner"])

    staff_users = User.objects.filter(is_staff=True)
    if owner:
        staff_users = staff_users | User.objects.filter(id=owner.id)

    for user in staff_users.distinct():
        VendorMembership.objects.get_or_create(
            vendor_id=vendor.id,
            user_id=user.id,
            defaults={
                "role_id": user.role_id,
                "is_owner": owner is not None and user.id == owner.id,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_vendor, migrations.RunPython.noop),
    ]

