# Generated by Django 5.2.8 on 2026-04-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_default_vendor_memberships"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="meta_access_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="meta_capi_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendor",
            name="meta_default_currency",
            field=models.CharField(default="BDT", max_length=10),
        ),
        migrations.AddField(
            model_name="vendor",
            name="meta_pixel_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendor",
            name="meta_pixel_id",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="vendor",
            name="meta_test_event_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendor",
            name="storefront_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
