# Generated by Django 5.2.8 on 2026-04-25 15:37

from django.db import migrations


def copy_siteconfig_meta_to_vendor(apps, schema_editor):
    SiteConfig = apps.get_model("store", "SiteConfig")
    Vendor = apps.get_model("vendors", "Vendor")

    vendor = Vendor.objects.order_by("created_at").first()
    site_config = SiteConfig.objects.order_by("created_at").first()

    if not vendor or not site_config:
        return

    vendor.meta_pixel_enabled = getattr(site_config, "meta_pixel_enabled", False)
    vendor.meta_pixel_id = getattr(site_config, "meta_pixel_id", "") or ""
    vendor.meta_capi_enabled = getattr(site_config, "meta_capi_enabled", False)
    vendor.meta_access_token = getattr(site_config, "meta_access_token", "") or ""
    vendor.meta_test_event_code = (
        getattr(site_config, "meta_test_event_code", "") or ""
    )
    vendor.meta_default_currency = (
        getattr(site_config, "meta_default_currency", "") or "BDT"
    )
    vendor.storefront_enabled = True
    vendor.save(
        update_fields=[
            "meta_pixel_enabled",
            "meta_pixel_id",
            "meta_capi_enabled",
            "meta_access_token",
            "meta_test_event_code",
            "meta_default_currency",
            "storefront_enabled",
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_merge_0002_siteconfig_fields"),
        ("vendors", "0003_vendor_meta_access_token_vendor_meta_capi_enabled_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_siteconfig_meta_to_vendor, migrations.RunPython.noop),
    ]

