export const queryKeys = {
	dashboard: "dashboard",
	me: "me",
	products: "products",
	productDetails: "productDetails",
	categories: "categories",
	orders: "orders",
	customers: "customers",
	reviews: "reviews",
	banners: "banners",
	announcements: "announcements",
	siteConfig: "siteConfig",
	variantTypes: "variantTypes",
	productVariants: "productVariants",
	coupons: "coupons",
	staff: "staff",
	roles: "roles",
	sales: "sales",
	wishlists: "wishlists",
} as const;
