# Generated by Django 5.2.8 on 2026-01-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="otpverification",
            name="otp_verific_mobile__f3663f_idx",
        ),
        migrations.RemoveField(
            model_name="otpverification",
            name="mobile_number",
        ),
        migrations.AddField(
            model_name="otpverification",
            name="email",
            field=models.EmailField(db_index=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="otpverification",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("registration", "Registration"),
                    ("guest_order", "Guest Order Tracking"),
                    ("password_reset", "Password Reset"),
                ],
                default="registration",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["email", "purpose", "is_verified", "expires_at"],
                name="otp_verific_email_50a67f_idx",
            ),
        ),
    ]
